# engine
add_subdirectory(./base)
add_subdirectory(./memory)
add_subdirectory(./time)
add_subdirectory(./logger)
add_subdirectory(./debug)
add_subdirectory(./math)
# 
add_subdirectory(./asset_baker)
add_subdirectory(./assets)
# 
add_subdirectory(./camera)
add_subdirectory(./input)
# add_subdirectory(./ui)
# 
add_subdirectory(./surface)
add_subdirectory(./renderer)
add_subdirectory(./ecs)
# 
add_subdirectory(./app)

# apps 
add_subdirectory(./mirror)
add_subdirectory(test)
