---
kind: pipeline
type: exec
name: amd64 — msvc
trigger:
  branch:
  - main
platform:
  os: windows
  arch: amd64

steps:
- name: unit tests
  shell: powershell
  commands: 
    - ./tools/ci/amd64/msvc/unit_tests.ps1

---
kind: pipeline
type: docker
name: amd64 — gcc
trigger:
  branch:
  - main

steps:
- name: unit tests
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/amd64/gcc/unit_tests.sh

- name: valgrind
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/amd64/gcc/valgrind.sh

---
kind: pipeline
type: docker
name: amd64 — clang
trigger:
  branch:
  - main

steps:
- name: code coverage
  image: ci:latest
  pull: if-not-exists
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN 
  commands:
    - ./tools/ci/amd64/clang/coverage.sh

- name: leak sanitizer
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/amd64/clang/lsan.sh

- name: memory sanitizer
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/amd64/clang/msan.sh

---
kind: pipeline
type: docker
name: static analysis
trigger:
  branch:
  - main

steps:
- name: clang tidy
  image: ci:latest
  pull: if-not-exists
  privileged: true
  commands:
    - ./tools/ci/static_analysis/clang_tidy.sh

- name: clang format
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/static_analysis/clang_format.sh

- name: cmake format
  image: ci:latest
  pull: if-not-exists
  commands:
    - ./tools/ci/static_analysis/cmake_format.sh

---
kind: pipeline
type: docker 
name: documentation — development
node:
  environment: ryali
trigger:
  branch:
  - main

steps:
- name: build and deploy
  image: documentation:latest
  pull: if-not-exists
  commands:
    - pwd
    - cd docs
    - mkdir generated
    - touch generated/changelogs.rst
    - touch generated/api.rst
    - sphinx-build -M html . .

    - rm -rf /light_docs_dev/*
    - mv ./html/* /light_docs_dev/

---

kind: pipeline
type: docker
name: documentation — production
node:
  environment: ryali
trigger:
  event:
  - tag

steps:
- name: build and deploy
  image: documentation:latest
  pull: if-not-exists
  commands:
    - cd docs
    - mkdir generated
    - touch generated/changelogs.rst
    - touch generated/api.rst
    - sphinx-build -M html . .

    - rm -rf /light_docs/*
    - mv ./html/* /light_docs/
