kind: pipeline
type: docker
name: linux_amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: clang format
    image: alpine_amd64__clang_format
    pull: if-not-exists
    commands: $(git rev-parse --show-toplevel)/tools/ci/alpine_amd64/script.sh
