kind: pipeline
type: docker
name: clang format

trigger:
  branch:
  - main

steps:
- name: clang format
  image: clang_format:latest
  pull: if-not-exists
  commands:
    - |
      set -e
      clang-format --version

      find ./modules -name '*.?pp' | while read -r file; do
        echo "Checking format for $file"
        if ! clang-format --dry-run --Werror "$file"; then
          echo "❌ Formatting issue detected in $file"
          exit 1
        fi
      done

      echo "✅ All files are properly formatted"
