name: CI

on:
  push:
    branches:
      - main

jobs:
  amd64-clang:
    runs-on: lina
    steps:
      - uses: actions/checkout@v4

      - name: code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./tools/ci/coverage.sh

      - name: undefined behavior sanitizer
        run: ./tools/ci/ubsan.sh

      - name: address sanitizer
        run: ./tools/ci/asan.sh

      - name: memory sanitizer
        run: ./tools/ci/msan.sh

      - name: thread sanitizer
        run: ./tools/ci/tsan.sh

      - name: valgrind
        run: ./tools/ci/valgrind.sh

  static-analysis:
    runs-on: lina
    steps:
      - uses: actions/checkout@v4

      - name: clang format
        run: ./tools/ci/clang_format.sh

      - name: cmake format
        run: ./tools/ci/cmake_format.sh

      - name: shell format
        run: ./tools/ci/shell_format.sh

      - name: shell check
        run: ./tools/ci/shell_check.sh

      - name: clang tidy
        run: ./tools/ci/clang_tidy.sh
