name: CI

on:
  push:
    branches:
      - main

jobs:
  cmake-format:
    runs-on: lina
    steps:
      - uses: actions/checkout@v4
      - name: cmake format
        run: ./tools/ci/cmake_format.sh
