name: codecov

on:
  push:
    branches:
      - main

jobs:
  codecov:
    runs-on: lina
    steps:
      - uses: actions/checkout@v4
      - name: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: ./tools/ci/coverage.sh
